### PR TITLE
[zuul] Add workflows to tempest

### PR DESCRIPTION
**Pull request by lpiwowar**
Let's test tempest workflows in the check / periodic job as well.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/1625

### CODE REVIEW

**Comment by lpiwowar** [comment]
Let's wait until the ci-framework PR gets merged -> https://github.com/openstack-k8s-operators/ci-framework/pull/1625

**Comment by lpiwowar** [comment]
recheck

We might potentially have an issue with the workflows. I want to see whether it is flaky issue or an issue specifically connected to our job.

**Comment by lpiwowar** [comment]
recheck

We might potentially have an issue with the workflows. I want to see whether it is flaky issue or an issue specifically connected to our job.

**Review by kopecmartin — APPROVED** [review]
lgtm

**Pull request merged**
