### PR TITLE
Disable AllowPrivilegeEscalation 

### PR DESCRIPTION
**Pull request by lpiwowar**
This PR ensures that test pods do not run with allowPrivilegeEscalation.
In order to be able to run pods without the privilege escalation flag,
the following changes had to be made:

- Removal of mounting of the localtime and machine-id files (required
  hostPath). These files are not required for successful functioning
  of the test-operator.

- Removal of the CAP_AUDIT_WRITE flag.

- Dropping of of all capabilities by default.

However, for certain set of test-operator functionalities the parameters
mentioned above are required to be enabled. Because of that we are
introducing privileged flag that can be used to turn on to above disabled
flags.

### CODE REVIEW

**Comment by lpiwowar** [comment]
[This ci-framework change](https://github.com/openstack-k8s-operators/ci-framework/pull/2295) must be merged first.

```
2024-09-03 12:29:56.767931 | controller | TASK [test_operator : Start tests - tempest kubeconfig={{ cifmw_openshift_kubeconfig }}, api_key={{ cifmw_openshift_token | default(omit)}}, context={{ cifmw_openshift_context | default(omit)}}, state=present, wait=True, definition={{ test_operator_cr }}] ***
2024-09-03 12:29:56.767945 | controller | Tuesday 03 September 2024  12:29:56 -0400 (0:00:00.027)       0:45:24.036 *****
2024-09-03 12:29:56.767959 | controller | fatal: [localhost]: FAILED! => changed=false
2024-09-03 12:29:56.911448 | controller |   msg: 'Failed to create object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"admission webhook \\"vtempest.kb.io\\" denied the request: Tempest.test-operator.openstack.org \\"tempest-tests\\" is invalid: Tempest.spec.TempestRun.ExtraRPMs: Invalid value: []string(nil): Tempest.Spec.Privileged must be enabled for this test configuration.","reason":"Invalid","details":{"name":"tempest-tests","group":"test-operator.openstack.org","kind":"Tempest","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: []string(nil): Tempest.Spec.Privileged must be enabled for this test configuration.","field":"Tempest.spec.TempestRun.ExtraRPMs"}]},"code":422}\n'''
```

**Comment by kopecmartin** [comment]
recheck

**Comment by lpiwowar** [comment]
Let's wait for the jobs to finish and maybe let's give a time to Ella to merge this (there might be some conflicts) -> [https://github.com/openstack-k8s-operators/test-operator/pull/200]. 

If by tomorrow morning Ella's patch is not ready to be merged. I'm merging this.

**Review by kopecmartin — APPROVED** [review]

**Pull request merged**
