### PR TITLE
[zuul] Enable tempest cleanup

### PR DESCRIPTION
**Pull request by lpiwowar**
This patch enables the tempest cleanup feature that cleans all
resources created during the tempest test execution.

Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/2381

### CODE REVIEW

**Comment by lpiwowar** [comment]
recheck

the upstream image should now contain the change

**Comment by lpiwowar** [comment]
recheck

**Comment by lpiwowar** [comment]
recheck

the test image `quay.io/lpiwowar0/openstack-tempest-all:v0.0.1` was not set as public ([here](https://logserver.rdoproject.org/16/216/41e791119dfe5774b007e5849834717f9fdcbd1a/github-check/podified-multinode-edpm-deployment-crc-test-operator/0f5b324/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/tempest-tests-full-workflow-step-0-7lqzg/tempest-tests-full-workflow-step-0-7lqzg-describe))

**Review by kopecmartin — APPROVED** [review]
lgtm

**Pull request merged**
