### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by omersch381**
This patch fixes a few typos. I used chatgpt to browse some docs source files and then I added some of those changes using `git add -i`, please don't hate me :(

### CODE REVIEW

**Review by kopecmartin — APPROVED** [review]
great initiative! Thanks

**Comment by lpiwowar** [comment]
Thanks a lot, @omersch381!:)

**Review by lpiwowar — APPROVED** [review]
LGTM!

**Comment by lpiwowar** [comment]
@omersch381 there is just a merge conflict that needs to be resolved before we merge this. Otherwise, LGTM!:)

**Comment by omersch381** [comment]
Done!

**Pull request merged**
