### PR TITLE
Test precommit checks

### PR DESCRIPTION
**Pull request by lpiwowar**

### CODE REVIEW

**Comment by lpiwowar** [comment]
No longer needed - just testing precommit checks

**Comment by stuggi** [comment]
tide testing

**Comment by lpiwowar** [comment]
No longer needed

**Comment by lpiwowar** [comment]
Testing here as well -> [https://github.com/openstack-k8s-operators/test-operator/pull/154]

**Comment by lpiwowar** [comment]
Looks like tide merged the change here -> https://github.com/openstack-k8s-operators/test-operator/pull/154

**Comment by stuggi** [comment]
seems all good, closing this test PR

**Pull request closed without merging**
