### PR TITLE
Remove TempestRegexp argument

### PR DESCRIPTION
**Pull request by afazekas**
Looks like it was not in use since the begning.
Users usually finds simpler to have explicit negative list,
even tough it is possible to consutuct a singe regexp.
Also possible to construct a single regexp on the operator side,
in case other way of passing would be prefered later on.

Moving the default allowedTests to the defaults.

Note: Consider moving the tempest run arguments
to sub structure.

### CODE REVIEW

**Comment by afazekas** [comment]
Added a second commit,
question do we want to structure the args deeper ?

**Comment by kopecmartin** [comment]
lgtm, tested and it all still works .. we can add --regex and --smoke support in a new commit

**Comment by kopecmartin** [comment]
it seems there is no bot? meh, i'll click the merge pull request button :D

**Pull request merged**
