### PR TITLE
Add link to guide video to the documentation

### PR DESCRIPTION
**Pull request by kstrenkova**
This patch adds a new note to the test operator documentation that contains link to a visual guide for problems user can encounter with Tempest.

### CODE REVIEW

**Review by lpiwowar — COMMENTED** [review]
LGTM! :+1: 

We just have to deal now with the failing check job. Can you please rebase this patch on top of main. There was a recent change in `.zuul.yaml` that should be fixing the issue [1].

[1] https://github.com/openstack-k8s-operators/test-operator/pull/110

**Comment by kstrenkova** [comment]
I have rebased the patch on top of main, hope it helps.

**Review by lpiwowar — APPROVED** [review]
LGTM

**Pull request merged**
