### PR TITLE
[Ansibletest] Enable ansibletest testing in check job

### PR DESCRIPTION
**Pull request by lpiwowar**

### CODE REVIEW

**Comment by lpiwowar** [comment]
recheck
NODE_FAILURE

**Comment by lpiwowar** [comment]
recheck

**Comment by lpiwowar** [comment]
recheck

I want to see whether this is flaky issue (it looks strange). The webhook should work and I know we are running the ansible-tests in some jobs:

```
2024-09-03 09:34:16.977582 | controller | fatal: [localhost]: FAILED! => changed=false
2024-09-03 09:34:17.181195 | controller |   msg: 'Failed to create object: b''{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \\"mansibletest.kb.io\\": failed to call webhook: Post \\"https://test-operator-controller-manager-service.openstack.svc:443/mutate-test-openstack-org-v1beta1-ansibletest?timeout=10s\\": no endpoints available for service \\"test-operator-controller-manager-service\\"","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \\"mansibletest.kb.io\\": failed to call webhook: Post \\"https://test-operator-controller-manager-service.openstack.svc:443/mutate-test-openstack-org-v1beta1-ansibletest?timeout=10s\\": no endpoints available for service \\"test-operator-controller-manager-service\\""}]},"code":500}\n'''
```

**Comment by lpiwowar** [comment]
It looks like this is a real issue. I need to investigate this. Probably best option for this we'll be the autohold.

**Comment by lpiwowar** [comment]
I see this failure in the logs:
```
2024-09-04T01:26:56Z	INFO	Observed a panic in reconciler: runtime error: index out of range [2] with length 2	{"controller": "tobiko", "controllerGroup": "test.openstack.org", "controllerKind": "Tobiko", "Tobiko": {"name":"tobiko-tests","namespace":"openstack"}, "namespace": "openstack", "name": "tobiko-tests", "reconcileID": "2a774443-aaed-400e-9ce4-a86d95790cee"}
panic: runtime error: index out of range [2] with length 2 [recovered]
	panic: runtime error: index out of range [2] with length 2

goroutine 322 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:116 +0x1fa
panic({0x1b11f20, 0xc002c89290})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/openstack-k8s-operators/test-operator/controllers.(*Reconciler).GetJobName(0x0?, {0x1beee80?, 0xc001830000?}, 0x0?)
	/remote-source/controllers/common.go:171 +0x345
github.com/openstack-k8s-operators/test-operator/controllers.(*Reconciler).JobExists(0xc0002e6880, {0x1eb92f0, 0xc000bf2b10}, {0x1ecf010?, 0xc001830000}, 0xc001830000?)
	/remote-source/controllers/common.go:466 +0x9f
github.com/openstack-k8s-operators/test-operator/controllers.(*TobikoReconciler).Reconcile(0xc0002e6880, {0x1eb92f0, 0xc000bf2b10}, {{{0xc000672f30?, 0x5?}, {0xc000672f20?, 0xc0004abd08?}}})
	/remote-source/controllers/tobiko_controller.go:246 +0x130e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ebb8c0?, {0x1eb92f0?, 0xc000bf2b10?}, {{{0xc000672f30?, 0xb?}, {0xc000672f20?, 0x0?}}})
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:119 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000273680, {0x1eb9248, 0xc000002d70}, {0x1a7ccc0?, 0xc00047e0c0?})
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:316 +0x3ca
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000273680, {0x1eb9248, 0xc000002d70})
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:266 +0x1c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.6/pkg/internal/controller/controller.go:223 +0x587
```

I think we should be unblocked by this PR -> https://github.com/openstack-k8s-operators/test-operator/pull/201

Let's rebase and see whether it is true.

**Review by kopecmartin — APPROVED** [review]

**Pull request merged**
