### PR TITLE
Use new nad.EnsureNetworksAnnotation() func to get NAD annotations

### PR DESCRIPTION
**Pull request by stuggi**
For BGP setup there is the need to set the default gateway to the additional interface defined via the multus annotations. To allow this a user can configure `ipam.gateway` in the NAD. EnsureNetworksAnnotation() will override the pod network default route by reading the NAD. If `ipam.gateway` is defined and not "", it gets set on the networks annotation as the `default-route`.

Jira: https://issues.redhat.com/browse/OSPRH-8680

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/579

### CODE REVIEW

**Comment by stuggi** [comment]
recheck

**Comment by lpiwowar** [comment]
@stuggi, the job previously failed on:

```
2024-11-13T17:18:36Z	ERROR	Reconciler error	{"controller": "tempest", "controllerGroup": "test.openstack.org", "controllerKind": "Tempest", "Tempest": {"name":"tempest-tests","namespace":"openstack"}, "namespace": "openstack", "name": "tempest-tests", "reconcileID": "97582aa0-1531-4fe1-84ae-883bbc64e5bf", "error": "Error getting network-attachment-definition ctlplane/openstack - no kind is registered for the type v1.NetworkAttachmentDefinition in scheme \"go/pkg/mod/k8s.io/apimachinery@v0.29.10/pkg/runtime/scheme.go:100\""}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:227
```

https://logserver.rdoproject.org/45/245/d549cb3236e38b4ffbd0271ece083f0e38de9cc7/github-check/podified-multinode-edpm-deployment-crc-test-operator/fc3ca3a/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/test-operator-controller-manager-5c9fbbdd8f-pqb72/logs/manager.log

**Comment by stuggi** [comment]
> @stuggi, the job previously failed on: `no kind is registered for the type v1.NetworkAttachmentDefinition in scheme \"go/pkg/mod/k8s.io/apimachinery@v0.29.10/pkg/runtime/scheme.go:100\"`
> 
> ```
> 2024-11-13T17:18:36Z	ERROR	Reconciler error	{"controller": "tempest", "controllerGroup": "test.openstack.org", "controllerKind": "Tempest", "Tempest": {"name":"tempest-tests","namespace":"openstack"}, "namespace": "openstack", "name": "tempest-tests", "reconcileID": "97582aa0-1531-4fe1-84ae-883bbc64e5bf", "error": "Error getting network-attachment-definition ctlplane/openstack - no kind is registered for the type v1.NetworkAttachmentDefinition in scheme \"go/pkg/mod/k8s.io/apimachinery@v0.29.10/pkg/runtime/scheme.go:100\""}
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
> 	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:329
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
> 	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:266
> sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
> 	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.6/pkg/internal/controller/controller.go:227
> ```
> 
> https://logserver.rdoproject.org/45/245/d549cb3236e38b4ffbd0271ece083f0e38de9cc7/github-check/podified-multinode-edpm-deployment-crc-test-operator/fc3ca3a/controller/ci-framework-data/logs/openstack-k8s-operators-openstack-must-gather/namespaces/openstack/pods/test-operator-controller-manager-5c9fbbdd8f-pqb72/logs/manager.log

ack, let me check

**Comment by stuggi** [comment]
@lpiwowar its fixed now. could you review/approve?

**Pull request merged**
